// Generates packages/react/dist/_ds-entry.mjs — a sync-only aggregate entry
// over packages/react/dist. The published package deliberately has no barrel
// file (see CLAUDE.md / .cursor/rules/no-barrel-files.mdc) and no "." export,
// but the design-sync converter needs ONE entry module to bundle into
// window.MiltinsonDS. This file is not part of the package's public API and is
// never published; it exists only so the converter has an entry to bundle.
//
// It must live INSIDE packages/react (not under .design-sync/): the converter
// walks UP from --entry to the nearest named package.json to decide PKG_DIR,
// and from .design-sync/ that walk lands on the monorepo root — which makes it
// read the repo's types/ dir instead of packages/react/dist and discover zero
// components. Writing into dist/ also means `dist/` gitignore covers it and
// every `pnpm build` (which rm -rf's dist) is followed by a regen.
//
// Re-run via cfg.buildCmd (see .design-sync/config.json) — never hand-edit the
// generated entry, edit this generator instead.
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const distRoot = resolve(here, '../packages/react/dist');

const modules = [];
(function walk(dir) {
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full);
    else if (entry.endsWith('.js')) modules.push(full);
  }
})(distRoot);

const pkgRoot = resolve(here, '../packages/react');
const repoRoot = resolve(here, '..');
const outFile = join(distRoot, '_ds-entry.mjs');
const real = modules.filter((m) => m !== outFile);

const banner = [
  '// GENERATED by .design-sync/gen-entry.mjs — do not edit by hand.',
  '// Sync-only aggregate entry; not part of the published package API.',
  '',
];

writeFileSync(
  outFile,
  [
    ...banner,
    ...real.map((m) => `export * from '${'./' + relative(distRoot, m).split('\\').join('/')}';`),
    '',
  ].join('\n'),
);

// Types-only twin. The converter resolves the package's type entry to
// <pkgDir>/index.d.ts (there is no "types" field and adding one would change
// the published package), and reads the component roster from that file's
// export set — with no such file it discovers zero components.
//
// This does NOT violate the repo's no-barrel rule. That rule exists because a
// RUNTIME root barrel makes consumers' bundlers pull in every re-exported
// module. This file is types-only (erased at build time), gitignored, and
// excluded from the published tarball by package.json `files: ["dist","src"]`
// — verified with `npm pack --dry-run` — so no consumer bundler can ever see
// it. Runtime consumers still import subpaths only.
writeFileSync(
  join(pkgRoot, 'index.d.ts'),
  [
    ...banner,
    '// Types-only; gitignored and excluded from the published tarball.',
    '',
    ...real.map(
      (m) =>
        `export * from '${'./' + relative(pkgRoot, m).replace(/\.js$/, '').split('\\').join('/')}';`,
    ),
    '',
  ].join('\n'),
);

console.error(
  `[gen-entry] wrote ${relative(repoRoot, outFile)} + ${relative(repoRoot, join(pkgRoot, 'index.d.ts'))} ` +
    `re-exporting ${real.length} dist modules`,
);
