// Generates the two aggregate entries the design-sync converter needs. The
// published package deliberately has no barrel file and no "." export (see
// CLAUDE.md / .cursor/rules/no-barrel-files.mdc), but the converter needs ONE
// module to bundle and ONE .d.ts to read the component roster from.
//
//   packages/react/_ds-entry.mjs  — value entry (gitignored, see below)
//   packages/react/index.d.ts     — types entry (COMMITTED, see below)
//
// Neither is part of the package's public API and neither is published: both
// sit in the package ROOT, which `files: ["dist","src"]` excludes from the
// tarball (verified with `npm pack --dry-run`). Keeping the value entry out of
// dist/ is deliberate — written there it WOULD ship, putting a barrel inside
// the published package. `exports` also has no "." so under moduleResolution
// "bundler"/"node16" a root import cannot resolve even in-repo. The no-barrel
// rule is about a RUNTIME barrel forcing consumers' bundlers to load every
// module; a .d.ts is erased at build time and can never reach a consumer.
//
// Why index.d.ts is committed while _ds-entry.mjs is not
// -----------------------------------------------------
// Not symmetry — failure modes. A missing _ds-entry.mjs is LOUD: the converter
// dies immediately on an unresolvable --entry. A missing index.d.ts is SILENT: the converter reports "exported PascalCase
// symbols: 0", emits a zero-component bundle, and BOTH package-build.mjs and
// package-validate.mjs still exit 0 ("✓ bundle is complete", "tokens-only
// DS"). A re-sync would happily publish an empty design system over a good
// one. Committing the file removes the only realistic trigger (missing on a
// fresh clone) and turns the remaining risk — drift — into reviewable diff
// noise: it changes only when a component enters or leaves the public surface,
// which is exactly what a reviewer should see. Same rationale as a committed
// API-surface report.
//
// Run `node .design-sync/gen-entry.mjs --check` to verify the committed file
// is current without writing (exits 1 on drift).
//
// Re-run via cfg.buildCmd — never hand-edit the generated files.
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CHECK = process.argv.includes('--check');

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '../packages/react');
const repoRoot = resolve(here, '..');
const distRoot = join(pkgRoot, 'dist');

if (!statSync(distRoot, { throwIfNoEntry: false })?.isDirectory()) {
  console.error(
    `[gen-entry] ${relative(repoRoot, distRoot)} is missing — run \`pnpm build\` first.`,
  );
  process.exit(1);
}

const modules = [];
(function walk(dir) {
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full);
    else if (entry.endsWith('.js')) modules.push(full);
  }
})(distRoot);

const valueEntry = join(pkgRoot, '_ds-entry.mjs');
const typesEntry = join(pkgRoot, 'index.d.ts');
const real = modules.filter((m) => m !== valueEntry);

// An empty roster is the failure this whole file exists to prevent — never
// write a barrel that would make the converter report zero components.
if (real.length === 0) {
  console.error(`[gen-entry] no modules found under ${relative(repoRoot, distRoot)} — aborting.`);
  process.exit(1);
}

const banner = (extra) => [
  '// GENERATED by .design-sync/gen-entry.mjs — do not edit by hand.',
  '// @internal — NOT the package public entry point. Import subpaths instead:',
  "//   import { Button } from '@elirobinson/react/components/atoms/Button';",
  ...extra,
  '',
];

const spec = (from, m, stripExt) => {
  const rel = relative(from, m).split('\\').join('/');
  return './' + (stripExt ? rel.replace(/\.js$/, '') : rel);
};

const valueSource = [
  ...banner(['// Sync-only value entry; bundled into window.MiltinsonDS.']),
  ...real.map((m) => `export * from '${spec(pkgRoot, m, false)}';`),
  '',
].join('\n');

const typesSource = [
  ...banner(['// Types-only; excluded from the published tarball by `files`.']),
  ...real.map((m) => `export * from '${spec(pkgRoot, m, true)}';`),
  '',
].join('\n');

if (CHECK) {
  const current = readFileSync(typesEntry, 'utf8').replace(/\r\n/g, '\n');
  // Compare export lines only — prettier owns the committed file's formatting.
  const lines = (s) => s.split('\n').filter((l) => l.startsWith('export '));
  if (lines(current).join('\n') !== lines(typesSource).join('\n')) {
    console.error(
      `[gen-entry] ${relative(repoRoot, typesEntry)} is STALE — run \`node .design-sync/gen-entry.mjs\` and commit the result.`,
    );
    process.exit(1);
  }
  console.error(
    `[gen-entry] ${relative(repoRoot, typesEntry)} is up to date (${real.length} modules).`,
  );
  process.exit(0);
}

writeFileSync(valueEntry, valueSource);
writeFileSync(typesEntry, typesSource);

console.error(
  `[gen-entry] wrote ${relative(repoRoot, valueEntry)} + ${relative(repoRoot, typesEntry)} ` +
    `re-exporting ${real.length} dist modules`,
);
