/* The self-hosting contract: importing tokens.css loads the webfonts from the
 * package itself, never from a third-party origin at runtime.
 *
 * tokens.css used to reach Geist and JetBrains Mono through a render-blocking
 * Google Fonts @import. That made every consumer silently depend on
 * fonts.googleapis.com — a hidden runtime dependency the package's own story
 * says it must not have, and one consumers had to strip with a PostCSS pass to
 * self-host. The faces now ship in src/fonts/, declared by the generated
 * src/fonts.css, which tokens.css @imports relatively — a bundler inlines it,
 * a plain <link> resolves it, and no request ever leaves the consumer's
 * origin.
 *
 * fonts.css and src/fonts/ are generated by scripts/build-fonts.mjs from the
 * pinned @fontsource-variable packages but committed, like src/tokens.json:
 * the committed copy is what publishes, so these tests pin it to its source of
 * truth rather than trusting the generator ran.
 */

import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { effectiveTokens, parseTokensCss } from './parse-tokens-css.mjs';

const srcDir = dirname(fileURLToPath(import.meta.url));
const tokensCss = readFileSync(join(srcDir, 'tokens.css'), 'utf8');
const fontsCssPath = join(srcDir, 'fonts.css');
const fontsCss = existsSync(fontsCssPath) ? readFileSync(fontsCssPath, 'utf8') : '';

const withoutComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, '');

/** The first (quoted) family of each font stack — what @font-face must supply. */
const stackFamilies = new Set(
  [...effectiveTokens(parseTokensCss(tokensCss)).values()]
    .filter((token) => /^--font-(sans|display|mono)$/.test(token.name))
    .map((token) => token.resolved.match(/'([^']+)'/)[1]),
);

const faces = [...withoutComments(fontsCss).matchAll(/@font-face\s*\{([^}]*)\}/g)].map(
  (match) => match[1],
);
const of = (face, property) => face.match(new RegExp(`${property}:\\s*([^;]+);`))?.[1].trim();

describe('tokens.css loads fonts from the package, not a third party', () => {
  it('names no http(s) origin anywhere — the Google Fonts @import is the regression', () => {
    expect(withoutComments(tokensCss)).not.toMatch(/https?:/);
  });

  it('imports ./fonts.css relatively, so every consumer of the file resolves it', () => {
    /* Relative, and in the BARE STRING form rather than url(). This assertion
       pinned the url() spelling for four releases, which is part of why issue
       #76 survived review: Lightning CSS inlines the bare form and leaves the
       url() form standing as a literal @import, which a consumer's Tailwind
       import then strands after real rules — dropping it, and every @font-face
       with it. import-order.test.mjs owns that invariant across every shipped
       stylesheet; this keeps the narrower fact that tokens.css reaches the
       faces through a relative sibling path at all. */
    expect(withoutComments(tokensCss)).toMatch(/@import\s+'\.\/fonts\.css'\s*;/);
  });
});

describe('fonts.css', () => {
  it('declares a face for exactly the families the font stacks name', () => {
    const declared = new Set(faces.map((face) => of(face, 'font-family')?.replace(/['"]/g, '')));
    expect(declared).toEqual(stackFamilies);
  });

  it('swaps rather than blocking, matching the display=swap the remote import had', () => {
    expect(faces.length).toBeGreaterThan(0);
    for (const face of faces) {
      expect(of(face, 'font-display')).toBe('swap');
    }
  });

  it('subsets by unicode-range, so a latin page downloads latin files only', () => {
    for (const face of faces) {
      expect(of(face, 'unicode-range')).toBeTruthy();
    }
  });

  it('stays unlayered, like tokens.css', () => {
    expect(withoutComments(fontsCss)).not.toMatch(/@layer\b/);
  });

  it('references only files that ship in src/fonts/, and every face resolves', () => {
    const urls = [...withoutComments(fontsCss).matchAll(/url\(([^)]+)\)/g)].map((match) =>
      match[1].replace(/['"]/g, ''),
    );
    expect(urls.length).toBeGreaterThan(0);
    for (const url of urls) {
      expect(url, 'font urls must be package-relative').toMatch(/^\.\/fonts\//);
      expect(existsSync(join(srcDir, url)), `${url} is not on disk`).toBe(true);
    }
  });
});

describe('the committed copies against their source of truth', () => {
  const resolve = createRequire(import.meta.url).resolve;
  const packageFor = (basename) =>
    dirname(
      resolve(
        `@fontsource-variable/${basename.startsWith('jetbrains-mono') ? 'jetbrains-mono' : 'geist'}/package.json`,
      ),
    );

  it('every shipped face is byte-identical to its pinned @fontsource-variable file', () => {
    const urls = [...withoutComments(fontsCss).matchAll(/url\(([^)]+)\)/g)].map((match) =>
      match[1].replace(/['"]/g, ''),
    );
    for (const url of urls) {
      const basename = url.split('/').pop();
      const committed = readFileSync(join(srcDir, url));
      const upstream = readFileSync(join(packageFor(basename), 'files', basename));
      expect(committed.equals(upstream), `${basename} drifted from @fontsource-variable`).toBe(
        true,
      );
    }
  });

  it('ships the SIL Open Font License both families are distributed under', () => {
    for (const family of ['geist', 'jetbrains-mono']) {
      const license = join(srcDir, 'fonts', `LICENSE-${family}.txt`);
      expect(existsSync(license), `${license} missing`).toBe(true);
      expect(readFileSync(license, 'utf8')).toContain('SIL OPEN FONT LICENSE');
    }
  });
});

describe('the brand mirror', () => {
  /* design-system-docs/ reaches the same files through symlinks, the way
     colors_and_type.css already mirrors tokens.css — the skill tarball and the
     docs site stage them dereferenced from there. */
  const docsDir = join(srcDir, '..', '..', '..', 'design-system-docs');

  it('mirrors fonts.css', () => {
    expect(readFileSync(join(docsDir, 'fonts.css'), 'utf8')).toBe(fontsCss);
  });

  it('mirrors every shipped font file', () => {
    const urls = [...withoutComments(fontsCss).matchAll(/url\(\.\/fonts\/([^)]+)\)/g)].map(
      (match) => match[1],
    );
    for (const basename of urls) {
      const mirrored = join(docsDir, 'fonts', basename);
      expect(existsSync(mirrored), `${mirrored} missing`).toBe(true);
      expect(readFileSync(mirrored).equals(readFileSync(join(srcDir, 'fonts', basename)))).toBe(
        true,
      );
    }
  });
});
