/* The two documents the design-project build writes that are neither component
 * API nor token data: the project's provenance note, and the stylesheet the
 * repo's mirrored guideline cards link to.
 *
 * They live here rather than inline in scripts/build-design-project.mjs for the
 * same reason adherence.mjs and guideline-cards.mjs do: they are content
 * generators, they are worth testing, and this package already keeps its
 * generators in one place. The script is orchestration.
 */

/** `a\b\c` -> `a/b/c`. Stylesheet paths are POSIX on both sides of the sync. */
export const toPosix = (path) => path.split(/[\\/]/).join('/');

/**
 * The exact set of project paths a push may write, derived rather than listed.
 *
 * The generated foundation cards have to be inside the boundary or the upload
 * rejects them, and they are whatever `buildGuidelineCards` emits — so they are
 * folded in from that roster instead of being restated. A hand-kept copy of the
 * card list is the same drift bug the card generator exists to remove, and it
 * would fail late and confusingly, at push time, on the twelfth card.
 *
 * The editorial cards in `guidelines/` belong to the project and never appear
 * here, which is what stops a push reaching them.
 *
 * @param {{ writes: string[] }} target the fixed part of the boundary
 * @param {{ path: string }[]} cards what the card builder actually emitted
 */
export function pushBoundary(target, cards) {
  return {
    ...target,
    writes: [...target.writes, ...cards.map(({ path }) => `guidelines/${path}`)],
  };
}

/**
 * The aggregate `design-system-docs/styles.css` that the mirrored guideline
 * cards link to. Relative `@import`s into the real component stylesheets rather
 * than a copy of them, so a card opens straight off the file system and can
 * never show stale CSS.
 *
 * @param {string[]} sheets stylesheet paths relative to src/components
 */
export function buildDocsStylesheet(sheets) {
  if (!sheets?.length) {
    throw new Error('buildDocsStylesheet: no component stylesheets supplied.');
  }
  return `${[
    '/* GENERATED by packages/ai-patterns/scripts/build-design-project.mjs.',
    '   Do not edit by hand — run `pnpm -F @elirobinson/ai-patterns build:design-project`.',
    '   The aggregate the guidelines/ cards link to, pointing at the real',
    '   component stylesheets rather than a copy of them. */',
    "@import './colors_and_type.css';",
    ...sheets.map((sheet) => `@import '../packages/react/src/components/${toPosix(sheet)}';`),
  ].join('\n')}\n`;
}

/**
 * The project's `github.md` — what it was built from, who owns which files, and
 * what is generated rather than written.
 *
 * Every number here is passed in from something counted at build time. The
 * hand-written copy this replaces asserted "five ui kits" while the project
 * carried thirteen, and nothing noticed.
 *
 * `kits` is deliberately a plain count supplied by the caller rather than
 * something this module goes and reads off disk. What it describes is the
 * *project's* contents, which no file in this repo can observe directly — the
 * caller has to say where its figure came from, and the rendered text says so
 * too, so a reader knows the number's provenance instead of trusting it.
 *
 * @param {object} input
 * @param {{ repo: string, branch: string }} input.target
 * @param {{ package: string, version: string, components: unknown[] }} input.manifest
 * @param {number} input.stylesheetCount
 * @param {number} input.tokenCount
 * @param {number} input.cardCount
 * @param {{ shared: number, projectOnly: number }} input.kits
 */
export function buildProvenanceDoc({
  target,
  manifest,
  stylesheetCount,
  tokenCount,
  cardCount,
  kits,
}) {
  return `${[
    `repo: ${target.repo}`,
    `branch: ${target.branch}`,
    '',
    '## Ownership',
    '',
    'Split by content type, one direction per file. Nothing here is edited by hand on',
    'both sides.',
    '',
    '| Owned by the repo (pushed here) | Owned by this project (pulled to the repo) |',
    '| --- | --- |',
    '| `tokens/tokens.css` | `guidelines/` editorial cards |',
    '| `components/**/*.css` | `ui_kits/`, `templates/`, `patterns/`, `slides/` |',
    '| `_adherence.oxlintrc.json` | `components/**/*.jsx` prototyping recreations |',
    '| `guidelines/` token cards | |',
    '| `SKILL.md`, `github.md` | |',
    '',
    '## Generated, not written',
    '',
    `- \`_adherence.oxlintrc.json\` — from \`${manifest.package}@${manifest.version}\`'s component`,
    '  manifest. Every rule, including the roster of exported component names.',
    '- `guidelines/` token cards — from `tokens.css`. A swatch card is a restatement of',
    '  the token scale, and a hand-written one drifts: the copy these replaced rendered',
    '  10 of the 13 ink steps.',
    '- `tokens/tokens.css` and every component stylesheet — copied verbatim from source.',
    '- `SKILL.md` and this file.',
    '',
    'Regenerate and push with `pnpm -F @elirobinson/ai-patterns build:design-project`,',
    'then write the paths named in `.push-plan.json`.',
    '',
    '## Counts',
    '',
    `- ${manifest.components.length} components in the published library`,
    `- ${stylesheetCount} component stylesheets, mirrored 1:1`,
    `- ${tokenCount} design tokens`,
    `- ${cardCount} generated foundation cards`,
    `- ${kits.shared + kits.projectOnly} ui kits, as of the last mirror into the repo —`,
    `  ${kits.shared} that also ship from the repo's \`ui_kits/\`, and ${kits.projectOnly} mirrored`,
    '  under `design-system-docs/_project-mirror/`, which does not ship. Counted from that',
    '  mirror, so it lags anything added here since.',
    '',
  ].join('\n')}`;
}
