/* The one llms.txt / llms-full.txt generator.
 *
 * Two callers render this corpus and there is exactly one implementation of it:
 *
 *   - `scripts/build-artifacts.mjs` stages the offline snapshot that ships in
 *     this package's tarball. It has a version stamp and no page prose.
 *   - `apps/docs` serves `/llms.txt` and `/llms-full.txt` at request time. It
 *     has the MDX prose the human pages render and a URL per component record,
 *     and no version stamp — a live site is never a stale snapshot of itself.
 *
 * Those four things are the *only* differences, and each is an optional
 * argument below, absent by default. Everything else — the intro, the import
 * rules, the prop tables, the constraint and token rendering, the component and
 * hook sections — is this file, once. It used to be two files that said in
 * their headers that they were twins, which is not a mechanism.
 *
 * Everything is a pure function of its inputs, so the shape can be tested
 * without touching a filesystem. The manifest argument is
 * `@elirobinson/react/manifest`; the reader here only ever reads, so a field
 * added there needs no change until this file wants to render it.
 */

/* Names the system, not a company. This line used to read "for <Company> products", which
   told every consumer the system was built for one of them — the boundary violation this
   issue exists to end, sitting in the first paragraph an agent reads. The placeholder is
   deliberate and not coyness: this file ships (`files` includes `src`), the removed string
   is itself on the brand denylist, and quoting it here would put back in a comment exactly
   what the edit took out of the prose. The system's own name stays; that is a kept
   decision (docs/agents/brand-boundary.md). */
const INTRO =
  'Miltinson Design System — tokens, React 19 components, and AI patterns for the ' +
  'products built on it. Ink-led palette with one amber accent, sharp radii, ' +
  'hairline borders, WCAG AA by default. Packages: @elirobinson/tokens, ' +
  '@elirobinson/react, @elirobinson/ai-patterns (GitHub Packages registry).';

const IMPORT_RULES = [
  'There are no barrel files. Every import names a subpath:',
  "  import '@elirobinson/tokens/tokens.css';",
  "  import '@elirobinson/react/styles.css';",
  "  import { Button } from '@elirobinson/react/components/atoms/Button';",
  "  import { useRovingFocus } from '@elirobinson/react/hooks/useRovingFocus';",
  "A bare import from '@elirobinson/react' does not resolve.",
].join('\n');

/**
 * The prefix every documented invocation of this package's binaries is built
 * from. It names the package explicitly because it has to: `pnpm dlx <pkg>
 * <bin>` reads the trailing word as an argument to an implied binary, and this
 * package ships two (`ds-resync`, `elirobinson-ds`), so pnpm cannot guess and
 * aborts with ERR_PNPM_DLX_MULTIPLE_BINS. That abort happens before the binary
 * is spawned — there is no process of ours in which to catch it — so the only
 * defence is that the broken form is never written down. Import this rather
 * than retyping it. `dlx.test.mjs` runs the result and fails the build if the
 * bare form reappears anywhere in the repo, which is what covers the markdown
 * that cannot import anything.
 */
export const DLX = 'pnpm --package=@elirobinson/ai-patterns dlx';

export const RESYNC_COMMAND = `${DLX} ds-resync artifacts --write`;

/**
 * The stamp is the whole point of a snapshot existing rather than a live query:
 * a reader (human or agent) has to be able to tell, without trusting anything
 * else, which package versions these prop tables describe. The docs site passes
 * no versions and gets no stamp, because it is not a snapshot.
 *
 * @param {import('./llms.js').Versions} versions
 */
export function versionStamp(versions) {
  return [
    `Snapshot of @elirobinson/react@${versions.react} and @elirobinson/tokens@${versions.tokens},`,
    `generated by @elirobinson/ai-patterns@${versions.aiPatterns}.`,
    '',
    'If the repo you are reading this in has a different @elirobinson/react installed, this',
    'file describes a different version than the code you are writing against. Do not trust',
    'it — re-run:',
    `  ${RESYNC_COMMAND}`,
    'and prefer `pnpm ds props <Name>`, which reads the installed package and cannot go stale.',
  ].join('\n');
}

/* The token list this file renders comes from `parseTokensCss` in
   @elirobinson/tokens — the one parser — which each caller runs before handing
   the result in. This module used to carry a copy of it. */

/**
 * The brand voice rules, extracted from design-system-docs/README.md's
 * CONTENT FUNDAMENTALS section. Extracted here rather than by each caller so
 * the packed snapshot and the docs site cannot cut the section differently —
 * and loudly, because a corpus that silently lost its voice rules is exactly
 * the state this section exists to end.
 *
 * @param {string} readme
 */
export function brandVoice(readme) {
  const section = readme.match(/^## CONTENT FUNDAMENTALS\s*\n([\s\S]*?)(?=\n## )/m);
  if (!section) {
    throw new Error(
      'brandVoice: no "## CONTENT FUNDAMENTALS" section in the brand README — ' +
        'the corpus would silently lose the voice rules.',
    );
  }
  /* The section is a managed block now — `name="voice"`, written from the voice
     pack — so the extracted range opens with the begin marker and its
     generated-note comment and closes with the end marker. Strip HTML comments
     before the separator, so what lands in the corpus is the same bytes it
     carried when the section was hand-authored. The trailing `---` divides two
     README sections and means nothing here, where nothing follows it. */
  return section[1]
    .replace(/<!--[\s\S]*?-->\n?/g, '')
    .replace(/\n---\s*$/, '')
    .trim();
}

/** One line per brand artifact; repo-only artifacts say so. */
function brandArtifactLine(artifact) {
  const components =
    artifact.components && artifact.components.length > 0
      ? ` (components: ${artifact.components.join(', ')})`
      : '';
  const repoOnly = artifact.ships ? '' : ' [repo-only — not in the published package]';
  return `- ${artifact.path} — ${artifact.title}${components}${repoOnly}`;
}

function propsTable(props) {
  if (!props || props.length === 0) {
    return '(no props of its own beyond inherited HTML attributes)';
  }

  const rows = props.map(
    (prop) =>
      `| ${prop.name} | \`${prop.type.replace(/\|/g, '\\|')}\` | ${prop.required ? 'yes' : 'no'} | ${
        prop.defaultValue ?? '—'
      } | ${prop.description || '—'} |`,
  );

  return [
    '| Prop | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function componentSection(component, appendix) {
  const exported = [
    component.name,
    ...component.subComponents.map((sub) => sub.name),
    ...component.hooks.map((hook) => hook.name),
  ].join(', ');

  const parts = [
    `### ${component.name} (${component.tier})`,
    '',
    component.description,
    '',
    `Import: \`import { ${exported} } from '${component.importSpecifier}';\``,
  ];

  if (component.stylesheetPaths.length > 0) {
    parts.push(`Styles: ${component.stylesheetPaths.join(', ')} (included in styles.css)`);
  }
  if (component.inherits) {
    parts.push(`Also accepts all \`${component.inherits}\` props.`);
  }

  parts.push('', propsTable(component.props));

  for (const sub of component.subComponents) {
    parts.push('', `#### ${sub.name}`, '', propsTable(sub.props));
    if (sub.inherits) parts.push(`Also accepts all \`${sub.inherits}\` props.`);
  }

  if (component.constraints.length > 0) {
    parts.push('', `Constraints: ${component.constraints.join(', ')} (see System constraints)`);
  }
  if (component.extractionGaps.length > 0) {
    parts.push(`Notes: ${component.extractionGaps.join('; ')}`);
  }

  for (const block of appendix(component)) {
    parts.push('', block);
  }

  return parts.join('\n');
}

/**
 * Components grouped by tier, in the order the manifest reports its tiers.
 *
 * Driven off `manifest.tiers` rather than a hardcoded ['atoms','molecules',
 * 'organisms'], which is how a tier added to @elirobinson/react used to drop
 * every component in it out of the corpus without a word. Anything the manifest
 * gives no tier — a flat layout reports `tier: null`, and a manifest older than
 * `tiers` gives none at all — is emitted after the tiers rather than silently
 * discarded.
 *
 * Both the index and the full corpus go through this, so the two never disagree
 * about what order the components are in.
 */
function orderedComponents(manifest) {
  const tiers = manifest.tiers ?? [];
  return [
    ...tiers.flatMap((tier) => manifest.components.filter((entry) => entry.tier === tier)),
    ...manifest.components.filter((entry) => !tiers.includes(entry.tier)),
  ];
}

/**
 * The index: what this system is, how to install it, and one line per component
 * and hook.
 *
 * @param {import('./llms.js').IndexInput} input
 */
export function llmsIndex({ manifest, versions, alsoAvailable }) {
  return [
    '# Miltinson Design System',
    '',
    `> ${INTRO}`,
    ...(versions ? ['', versionStamp(versions)] : []),
    '',
    '## Install',
    '',
    'GitHub Packages registry — .npmrc with @elirobinson:registry=https://npm.pkg.github.com',
    'and a PAT with read:packages. The token must go in the user-level npmrc, not the',
    "project's — pnpm 10 ignores registry credentials in a project .npmrc. Then:",
    '  pnpm config set "//npm.pkg.github.com/:_authToken" <pat>',
    '  pnpm add @elirobinson/tokens @elirobinson/react',
    '',
    IMPORT_RULES,
    '',
    ...(alsoAvailable ? [`## ${alsoAvailable.heading}`, '', ...alsoAvailable.entries, ''] : []),
    '## Components',
    '',
    ...orderedComponents(manifest).map(
      (component) =>
        `- ${component.name} (${component.tier}) — ${component.description} — import '${component.importSpecifier}'`,
    ),
    '',
    '## Hooks',
    '',
    ...manifest.hooks.map(
      (hook) =>
        `- ${hook.name} — ${hook.description.split(/[.\n]/)[0].trim()}. — import '${hook.importSpecifier}'`,
    ),
    '',
  ].join('\n');
}

/**
 * The full corpus: constraints, tokens, every component with its prop table,
 * every hook, and whatever narrative prose the caller has.
 *
 * @param {import('./llms.js').FullInput} input
 */
export function llmsFull({
  manifest,
  contracts,
  tokens,
  versions,
  prose = {},
  componentAppendix = () => [],
  brand,
}) {
  const constraintEntries = Object.entries(contracts.componentConstraints ?? {});
  const foundations = prose.foundations ?? [];
  const patterns = prose.patterns ?? [];

  const parts = [
    '# Miltinson Design System — full corpus',
    '',
    `> ${INTRO}`,
    ...(versions ? ['', versionStamp(versions)] : []),
    '',
    '## System constraints (machine-checkable ids from @elirobinson/ai-patterns/contracts)',
    '',
    ...constraintEntries.map(
      ([id, entry]) => `- **${id}** — ${entry.summary} Check: ${entry.check}`,
    ),
    '',
    `UI contracts: minimum touch target ${contracts.uiContracts.minimumTouchTarget} ` +
      `(scoped — see touch-target-dense). Dense floor: ` +
      `${contracts.uiContracts.minimumTouchTargetDense} Focus-visible required: ` +
      `${contracts.uiContracts.focusVisibleRequired}, contrast level ${contracts.uiContracts.contrastLevel}.`,
    '',
    '## Import rules',
    '',
    IMPORT_RULES,
    '',
    '## Design tokens (every token stylesheet @elirobinson/tokens declares, via readTokenStylesheets())',
    '',
    ...tokens.map(
      (token) => `- \`${token.name}: ${token.value}\`${token.comment ? ` — ${token.comment}` : ''}`,
    ),
  ];

  if (foundations.length > 0) {
    parts.push('', '## Foundations');
    for (const page of foundations) {
      parts.push('', page);
    }
  }

  parts.push('', '## Components');
  for (const component of orderedComponents(manifest)) {
    parts.push('', componentSection(component, componentAppendix));
  }

  parts.push('', '## Hooks');
  for (const hook of manifest.hooks) {
    parts.push(
      '',
      `### ${hook.name}`,
      '',
      `Import: \`import { ${hook.name} } from '${hook.importSpecifier}';\``,
    );
    if (hook.description) parts.push('', hook.description);
  }

  if (patterns.length > 0) {
    parts.push(
      '',
      '## Patterns',
      '',
      'These are recipes composed from the primitives above — they are NOT importable components.',
    );
    for (const page of patterns) {
      parts.push('', page);
    }
  }

  if (brand) {
    /* Loudly, and here rather than at the surface: the id is the whole point of the
       section's new framing, and a corpus published saying `pack: undefined` would be a
       worse claim than the one this replaced. This renderer is pure and cannot look the
       id up itself, so it refuses the input instead. */
    if (!brand.packId) {
      throw new Error(
        'llmsFull: brand.packId is required — the voice section names the pack in force, ' +
          'and a corpus that cannot name it should not claim to carry one.',
      );
    }

    parts.push(
      '',
      '## Voice',
      '',
      `The voice pack in force (pack: ${brand.packId}). Prop tables and tokens make a page`,
      'correct; a voice pack makes it sound like a particular product. This one is the',
      'default this system ships, not a rule of the system — a product declares its own',
      'with `ds init --voice` and this section follows it.',
    );
    if (brand.note) {
      parts.push('', brand.note);
    }
    parts.push('', brandVoice(brand.readme));
    if (brand.artifacts && brand.artifacts.length > 0) {
      parts.push('', '### Brand artifacts', '', ...brand.artifacts.map(brandArtifactLine));
    }
  }

  /* Both outputs end with a newline: one is written to a file, the other is
     served as text/plain, and neither reader benefits from a truncated last
     line. */
  parts.push('');
  return parts.join('\n');
}
