/* Builds the `llms.txt` / `llms-full.txt` snapshot that ships in the tarball.
 *
 * The docs site builds the same corpus at request time from live sources. This
 * is the offline twin: it derives from the *committed*
 * `apps/docs/src/generated/component-manifest.json`, the committed
 * `packages/tokens/src/tokens.css`, and this package's own `contracts.json` —
 * so packing never has to build `apps/docs`. The price is that the MDX prose
 * the site interleaves is absent here, which the header says out loud rather
 * than letting a reader assume this is the whole corpus.
 *
 * Everything is a pure function of its inputs so the shape can be tested
 * without touching a filesystem.
 */

const INTRO =
  'Miltinson Design System — tokens, React 19 components, and AI patterns for ' +
  'Miltinson Technologies products. Ink-led palette with one amber accent, sharp radii, ' +
  'hairline borders, WCAG AA by default. Packages: @elirobinson/tokens, ' +
  '@elirobinson/react, @elirobinson/ai-patterns (GitHub Packages registry).';

const IMPORT_RULES = [
  'There are no barrel files. Every import names a subpath:',
  "  import '@elirobinson/tokens/tokens.css';",
  "  import '@elirobinson/react/styles.css';",
  "  import { Button } from '@elirobinson/react/components/atoms/Button';",
  "  import { useRovingFocus } from '@elirobinson/react/hooks/useRovingFocus';",
  "A bare import from '@elirobinson/react' does not resolve.",
].join('\n');

export const RESYNC_COMMAND = 'pnpm dlx @elirobinson/ai-patterns ds-resync artifacts --write';

/**
 * The stamp is the whole point of this file existing as a snapshot rather than
 * a live query: a reader (human or agent) has to be able to tell, without
 * trusting anything else, which package versions these prop tables describe.
 *
 * @param {{ aiPatterns: string, react: string, tokens: string }} versions
 */
export function versionStamp(versions) {
  return [
    `Snapshot of @elirobinson/react@${versions.react} and @elirobinson/tokens@${versions.tokens},`,
    `generated by @elirobinson/ai-patterns@${versions.aiPatterns}.`,
    '',
    'If the repo you are reading this in has a different @elirobinson/react installed, this',
    'file describes a different version than the code you are writing against. Do not trust',
    'it — re-run:',
    `  ${RESYNC_COMMAND}`,
    'and prefer `pnpm ds props <Name>`, which reads the installed package and cannot go stale.',
  ].join('\n');
}

/**
 * Token names, values, and their trailing comments, straight out of the
 * committed `tokens.css`. `var()` chains are followed so a reader gets a
 * concrete value without having to resolve the graph by hand.
 */
export function parseTokensCss(css) {
  const root = css.match(/:root\s*\{([\s\S]*?)\n\}/)?.[1] ?? '';
  const raw = [...root.matchAll(/(--[\w-]+):\s*([^;]+);(?:[ \t]*\/\*\s*([\s\S]*?)\s*\*\/)?/g)].map(
    (match) => ({
      name: match[1],
      value: match[2].trim(),
      comment: match[3]?.replace(/\s+/g, ' ') ?? null,
    }),
  );

  const byName = new Map(raw.map((token) => [token.name, token.value]));
  const resolve = (value, depth = 0) => {
    if (depth > 8) return value;
    return value.replace(/var\((--[\w-]+)\)/g, (whole, name) => {
      const target = byName.get(name);
      return target ? resolve(target, depth + 1) : whole;
    });
  };

  return raw.map((token) => ({ ...token, resolved: resolve(token.value) }));
}

function propsTable(props) {
  if (!props || props.length === 0) {
    return '(no props of its own beyond inherited HTML attributes)';
  }

  const rows = props.map(
    (prop) =>
      `| ${prop.name} | \`${prop.type.replace(/\|/g, '\\|')}\` | ${prop.required ? 'yes' : 'no'} | ${
        prop.defaultValue ?? '—'
      } | ${prop.description || '—'} |`,
  );

  return [
    '| Prop | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function componentSection(component) {
  const exported = [
    component.name,
    ...component.subComponents.map((sub) => sub.name),
    ...component.hooks.map((hook) => hook.name),
  ].join(', ');

  const parts = [
    `### ${component.name} (${component.tier})`,
    '',
    component.description,
    '',
    `Import: \`import { ${exported} } from '${component.importPath}';\``,
  ];

  if (component.stylesheetPaths.length > 0) {
    parts.push(`Styles: ${component.stylesheetPaths.join(', ')} (included in styles.css)`);
  }
  if (component.inherits) {
    parts.push(`Also accepts all \`${component.inherits}\` props.`);
  }

  parts.push('', propsTable(component.props));

  for (const sub of component.subComponents) {
    parts.push('', `#### ${sub.name}`, '', propsTable(sub.props));
    if (sub.inherits) parts.push(`Also accepts all \`${sub.inherits}\` props.`);
  }

  if (component.constraints.length > 0) {
    parts.push('', `Constraints: ${component.constraints.join(', ')} (see System constraints)`);
  }
  if (component.extractionGaps.length > 0) {
    parts.push(`Notes: ${component.extractionGaps.join('; ')}`);
  }

  return parts.join('\n');
}

/** @param {{ manifest: object, versions: object }} input */
export function llmsIndex({ manifest, versions }) {
  return [
    '# Miltinson Design System',
    '',
    `> ${INTRO}`,
    '',
    versionStamp(versions),
    '',
    '## Install',
    '',
    'GitHub Packages registry — .npmrc with @elirobinson:registry=https://npm.pkg.github.com',
    'and a PAT with read:packages. The token must go in the user-level npmrc, not the',
    "project's — pnpm 10 ignores registry credentials in a project .npmrc. Then:",
    '  pnpm config set "//npm.pkg.github.com/:_authToken" <pat>',
    '  pnpm add @elirobinson/tokens @elirobinson/react',
    '',
    IMPORT_RULES,
    '',
    '## The rest of this snapshot',
    '',
    '- `llms-full.txt` — every token, every constraint, and every component with its prop table',
    '- `pnpm ds` / `pnpm ds props <Name>` — the same information read live from the installed',
    '  package. Always authoritative; this file is a convenience for reading in bulk.',
    '',
    '## Components',
    '',
    ...manifest.components.map(
      (component) =>
        `- ${component.name} (${component.tier}) — ${component.description} — import '${component.importPath}'`,
    ),
    '',
    '## Hooks',
    '',
    ...manifest.hooks.map(
      (hook) =>
        `- ${hook.name} — ${hook.description.split(/[.\n]/)[0].trim()}. — import '${hook.importPath}'`,
    ),
    '',
  ].join('\n');
}

/** @param {{ manifest: object, contracts: object, tokens: Array, versions: object }} input */
export function llmsFull({ manifest, contracts, tokens, versions }) {
  const constraintEntries = Object.entries(contracts.componentConstraints ?? {});

  const parts = [
    '# Miltinson Design System — full corpus',
    '',
    `> ${INTRO}`,
    '',
    versionStamp(versions),
    '',
    '## System constraints (machine-checkable ids from @elirobinson/ai-patterns/contracts)',
    '',
    ...constraintEntries.map(
      ([id, entry]) => `- **${id}** — ${entry.summary} Check: ${entry.check}`,
    ),
    '',
    `UI contracts: minimum touch target ${contracts.uiContracts.minimumTouchTarget} ` +
      `(scoped — see touch-target-dense), focus-visible required: ` +
      `${contracts.uiContracts.focusVisibleRequired}, contrast level ${contracts.uiContracts.contrastLevel}.`,
    '',
    '## Import rules',
    '',
    IMPORT_RULES,
    '',
    '## Design tokens (from @elirobinson/tokens/tokens.css)',
    '',
    ...tokens.map(
      (token) => `- \`${token.name}: ${token.value}\`${token.comment ? ` — ${token.comment}` : ''}`,
    ),
    '',
    '## Components',
  ];

  for (const tier of ['atoms', 'molecules', 'organisms']) {
    for (const component of manifest.components.filter((entry) => entry.tier === tier)) {
      parts.push('', componentSection(component));
    }
  }

  parts.push('', '## Hooks');
  for (const hook of manifest.hooks) {
    parts.push(
      '',
      `### ${hook.name}`,
      '',
      `Import: \`import { ${hook.name} } from '${hook.importPath}';\``,
    );
    if (hook.description) parts.push('', hook.description);
  }

  parts.push('');
  return parts.join('\n');
}
