import { parseTokensCss } from '@elirobinson/tokens/parse-tokens-css';
import { describe, expect, it } from 'vitest';

import { llmsFull, llmsIndex, versionStamp } from './llms.mjs';

const versions = { aiPatterns: '0.5.0', react: '1.2.0', tokens: '0.3.0' };

/* Trimmed to the shape the real component-manifest.json has, so the generator
   is exercised against the same fields it reads in production. */
const manifest = {
  components: [
    {
      name: 'Button',
      slug: 'button',
      tier: 'atoms',
      importPath: '@elirobinson/react/components/atoms/Button',
      stylesheetPaths: ['@elirobinson/react/styles/atoms/Button.css'],
      description: 'The primary action control.',
      inherits: 'ButtonHTMLAttributes<HTMLButtonElement>',
      props: [
        {
          name: 'variant',
          type: '"primary" | "ghost"',
          required: false,
          defaultValue: 'primary',
          description: '',
        },
      ],
      subComponents: [],
      hooks: [],
      exportedTypes: ['ButtonProps'],
      constraints: ['forward-ref'],
      extractionGaps: [],
    },
    {
      name: 'Dialog',
      slug: 'dialog',
      tier: 'organisms',
      importPath: '@elirobinson/react/components/organisms/Dialog',
      stylesheetPaths: [],
      description: 'Modal dialog.',
      inherits: '',
      props: [],
      subComponents: [{ name: 'DialogTitle', description: '', inherits: '', props: [] }],
      hooks: [],
      exportedTypes: [],
      constraints: [],
      extractionGaps: ['ref type not extracted'],
    },
  ],
  hooks: [
    {
      name: 'useClickOutside',
      importPath: '@elirobinson/react/hooks/useClickOutside',
      description: 'Calls back when a click lands outside.\nSecond paragraph.',
    },
  ],
};

const contracts = {
  componentConstraints: {
    'forward-ref': { summary: 'Forwards its ref.', check: 'eslint' },
  },
  uiContracts: { minimumTouchTarget: '44x44', focusVisibleRequired: true, contrastLevel: 'AA' },
};

const tokens = parseTokensCss(`
:root {
  --ink-500: #333; /* base ink */
  --fg: var(--ink-500);
}
`);

/* parseTokensCss itself is tested in @elirobinson/tokens, which owns it. */

describe('versionStamp', () => {
  it('names the react version the snapshot describes', () => {
    expect(versionStamp(versions)).toContain('@elirobinson/react@1.2.0');
  });

  it('tells the reader what to do when the versions disagree', () => {
    expect(versionStamp(versions)).toContain('ds-resync artifacts --write');
    expect(versionStamp(versions)).toContain('pnpm ds props');
  });
});

describe('llmsIndex', () => {
  const text = llmsIndex({ manifest, versions });

  it('is stamped with the versions it was generated against', () => {
    expect(text).toContain('Snapshot of @elirobinson/react@1.2.0 and @elirobinson/tokens@0.3.0');
    expect(text).toContain('generated by @elirobinson/ai-patterns@0.5.0');
  });

  it('lists every component with its tier and import path', () => {
    expect(text).toContain(
      "- Button (atoms) — The primary action control. — import '@elirobinson/react/components/atoms/Button'",
    );
    expect(text).toContain('- Dialog (organisms)');
  });

  it('lists hooks, cut to their first sentence', () => {
    expect(text).toContain('- useClickOutside — Calls back when a click lands outside. — import');
    expect(text).not.toContain('Second paragraph');
  });
});

describe('llmsFull', () => {
  const text = llmsFull({ manifest, contracts, tokens, versions });

  it('carries the same version stamp as the index', () => {
    expect(text).toContain('Snapshot of @elirobinson/react@1.2.0');
  });

  it('renders a prop table per component', () => {
    expect(text).toContain('| Prop | Type | Required | Default | Description |');
    expect(text).toContain('| variant | `"primary" \\| "ghost"` | no | primary | — |');
  });

  it('says so plainly when a component has no props of its own', () => {
    expect(text).toContain('(no props of its own beyond inherited HTML attributes)');
  });

  it('includes sub-components, constraints, and extraction gaps', () => {
    expect(text).toContain('#### DialogTitle');
    expect(text).toContain('Constraints: forward-ref');
    expect(text).toContain('Notes: ref type not extracted');
  });

  it('emits components in tier order, atoms first', () => {
    expect(text.indexOf('### Button (atoms)')).toBeLessThan(text.indexOf('### Dialog (organisms)'));
  });

  it('includes the tokens and the machine-checkable constraint ids', () => {
    expect(text).toContain('- `--ink-500: #333` — base ink');
    expect(text).toContain('- **forward-ref** — Forwards its ref. Check: eslint');
    expect(text).toContain('minimum touch target 44x44');
  });

  it('escapes pipes in union types so the markdown table survives', () => {
    expect(text).not.toMatch(/\| "primary" \| "ghost" \|/);
  });
});
