/* The corpus generator, tested once, here, against a fixture manifest.
 *
 * This is where the *shared* behaviour lives — prop tables, tier ordering,
 * constraint and token rendering, pipe escaping — because there is one
 * implementation of it. Each caller tests only its own half of the contract:
 * apps/docs/src/lib/ai-corpus.test.ts covers the prose and record links it
 * supplies, and build-artifacts is covered by the resync/artifacts suite.
 */

import { parseTokensCss } from '@elirobinson/tokens/parse-tokens-css';
import { describe, expect, it } from 'vitest';

import { brandVoice, llmsFull, llmsIndex, versionStamp } from './llms.mjs';

const versions = { aiPatterns: '0.5.0', react: '1.2.0', tokens: '0.3.0' };

/* Trimmed to the shape @elirobinson/react/manifest has, so the generator is
   exercised against the same fields it reads in production. */
const manifest = {
  tiers: ['atoms', 'organisms'],
  components: [
    {
      name: 'Button',
      slug: 'button',
      tier: 'atoms',
      importSpecifier: '@elirobinson/react/components/atoms/Button',
      stylesheetPaths: ['@elirobinson/react/styles/atoms/Button.css'],
      description: 'The primary action control.',
      inherits: 'ButtonHTMLAttributes<HTMLButtonElement>',
      props: [
        {
          name: 'variant',
          type: '"primary" | "ghost"',
          required: false,
          defaultValue: 'primary',
          description: '',
        },
      ],
      subComponents: [],
      hooks: [],
      constraints: ['forward-ref'],
      extractionGaps: [],
    },
    {
      name: 'Dialog',
      slug: 'dialog',
      tier: 'organisms',
      importSpecifier: '@elirobinson/react/components/organisms/Dialog',
      stylesheetPaths: [],
      description: 'Modal dialog.',
      inherits: '',
      props: [],
      subComponents: [{ name: 'DialogTitle', description: '', inherits: '', props: [] }],
      hooks: [],
      constraints: [],
      extractionGaps: ['ref type not extracted'],
    },
  ],
  hooks: [
    {
      name: 'useClickOutside',
      importSpecifier: '@elirobinson/react/hooks/useClickOutside',
      description: 'Calls back when a click lands outside.\nSecond paragraph.',
    },
  ],
};

const contracts = {
  componentConstraints: {
    'forward-ref': { summary: 'Forwards its ref.', check: 'eslint' },
  },
  uiContracts: { minimumTouchTarget: '44x44', focusVisibleRequired: true, contrastLevel: 'AA' },
};

const tokens = parseTokensCss(`
:root {
  --ink-500: #333; /* base ink */
  --fg: var(--ink-500);
}
`);

/* parseTokensCss itself is tested in @elirobinson/tokens, which owns it. */

describe('versionStamp', () => {
  it('names the react version the snapshot describes', () => {
    expect(versionStamp(versions)).toContain('@elirobinson/react@1.2.0');
  });

  it('tells the reader what to do when the versions disagree', () => {
    expect(versionStamp(versions)).toContain('ds-resync artifacts --write');
    expect(versionStamp(versions)).toContain('pnpm ds props');
  });
});

describe('llmsIndex', () => {
  const text = llmsIndex({ manifest, versions });

  it('is stamped with the versions it was generated against', () => {
    expect(text).toContain('Snapshot of @elirobinson/react@1.2.0 and @elirobinson/tokens@0.3.0');
    expect(text).toContain('generated by @elirobinson/ai-patterns@0.5.0');
  });

  it('carries no stamp when no versions are given — a live corpus is not a snapshot', () => {
    expect(llmsIndex({ manifest })).not.toContain('Snapshot of');
  });

  it('lists every component with its tier and import specifier', () => {
    expect(text).toContain(
      "- Button (atoms) — The primary action control. — import '@elirobinson/react/components/atoms/Button'",
    );
    expect(text).toContain('- Dialog (organisms)');
  });

  it('lists hooks, cut to their first sentence', () => {
    expect(text).toContain('- useClickOutside — Calls back when a click lands outside. — import');
    expect(text).not.toContain('Second paragraph');
  });

  it('states the no-barrel rule', () => {
    expect(text).toContain('no barrel files');
  });

  it('points at whatever else the caller publishes, in the caller’s own terms', () => {
    const withLinks = llmsIndex({
      manifest,
      alsoAvailable: { heading: 'Machine-readable docs', entries: ['- /r/<slug>.json'] },
    });

    expect(withLinks).toContain('## Machine-readable docs');
    expect(withLinks).toContain('- /r/<slug>.json');
    expect(text).not.toContain('## Machine-readable docs');
  });
});

describe('llmsFull', () => {
  const text = llmsFull({ manifest, contracts, tokens, versions });

  it('carries the same version stamp as the index', () => {
    expect(text).toContain('Snapshot of @elirobinson/react@1.2.0');
  });

  it('renders a prop table per component', () => {
    expect(text).toContain('| Prop | Type | Required | Default | Description |');
    expect(text).toContain('| variant | `"primary" \\| "ghost"` | no | primary | — |');
  });

  it('says so plainly when a component has no props of its own', () => {
    expect(text).toContain('(no props of its own beyond inherited HTML attributes)');
  });

  it('includes sub-components, constraints, and extraction gaps', () => {
    expect(text).toContain('#### DialogTitle');
    expect(text).toContain('Constraints: forward-ref');
    expect(text).toContain('Notes: ref type not extracted');
  });

  it('includes the tokens and the machine-checkable constraint ids', () => {
    expect(text).toContain('- `--ink-500: #333` — base ink');
    expect(text).toContain('- **forward-ref** — Forwards its ref. Check: eslint');
    expect(text).toContain('minimum touch target 44x44');
  });

  it('escapes pipes in union types so the markdown table survives', () => {
    expect(text).not.toMatch(/\| "primary" \| "ghost" \|/);
  });

  it('ends with a newline, so neither a file nor a text/plain body is truncated', () => {
    expect(text.endsWith('\n')).toBe(true);
  });

  describe('tier ordering', () => {
    it('emits components in the order the manifest reports its tiers', () => {
      expect(text.indexOf('### Button (atoms)')).toBeLessThan(
        text.indexOf('### Dialog (organisms)'),
      );

      const reversed = llmsFull({
        manifest: { ...manifest, tiers: ['organisms', 'atoms'] },
        contracts,
        tokens,
      });
      expect(reversed.indexOf('### Dialog (organisms)')).toBeLessThan(
        reversed.indexOf('### Button (atoms)'),
      );
    });

    it('emits a component whose tier the manifest never lists, rather than dropping it', () => {
      /* The bug this replaces: both generators hardcoded the three tier names,
         so a tier added to @elirobinson/react vanished from the corpus. */
      const narrowed = llmsFull({
        manifest: { ...manifest, tiers: ['atoms'] },
        contracts,
        tokens,
      });

      expect(narrowed).toContain('### Dialog (organisms)');
      expect(narrowed.indexOf('### Button (atoms)')).toBeLessThan(
        narrowed.indexOf('### Dialog (organisms)'),
      );
    });

    it('emits each component exactly once', () => {
      expect(text.match(/^### Button /gm)).toHaveLength(1);
    });

    it('orders the index the same way as the full corpus', () => {
      /* One corpus, one order. These are two files a reader flips between; a
         tier order applied to only one of them is worse than neither. */
      const reversed = { ...manifest, tiers: ['organisms', 'atoms'] };
      const index = llmsIndex({ manifest: reversed });
      const full = llmsFull({ manifest: reversed, contracts, tokens });

      expect(index.indexOf('- Dialog (organisms)')).toBeLessThan(index.indexOf('- Button (atoms)'));
      expect(full.indexOf('### Dialog (organisms)')).toBeLessThan(
        full.indexOf('### Button (atoms)'),
      );
    });

    it('falls back to manifest order when the manifest reports no tiers at all', () => {
      /* An install predating `tiers`. Degrading to the manifest's own order
         beats emitting an empty component list. */
      const untiered = { components: manifest.components, hooks: manifest.hooks };

      expect(llmsIndex({ manifest: untiered })).toContain('- Button (atoms)');
      expect(llmsFull({ manifest: untiered, contracts, tokens })).toContain(
        '### Dialog (organisms)',
      );
    });
  });

  describe('caller-supplied material', () => {
    it('appends nothing to a component section by default', () => {
      expect(text).not.toContain('Machine-readable record:');
    });

    it('appends each block a caller returns, in order', () => {
      const withAppendix = llmsFull({
        manifest,
        contracts,
        tokens,
        componentAppendix: (component) => [
          `prose for ${component.slug}`,
          `record: ${component.slug}`,
        ],
      });

      expect(withAppendix).toContain('prose for button');
      expect(withAppendix.indexOf('prose for button')).toBeLessThan(
        withAppendix.indexOf('record: button'),
      );
    });

    it('omits the narrative sections when the caller has no prose', () => {
      expect(text).not.toContain('## Foundations');
      expect(text).not.toContain('## Patterns');
    });

    it('places foundations before the components and patterns after the hooks', () => {
      const withProse = llmsFull({
        manifest,
        contracts,
        tokens,
        prose: { foundations: ['Colour is ink-led.'], patterns: ['A header is a recipe.'] },
      });

      expect(withProse).toContain('Colour is ink-led.');
      expect(withProse).toContain('NOT importable components');
      expect(withProse.indexOf('## Foundations')).toBeLessThan(withProse.indexOf('## Components'));
      expect(withProse.indexOf('## Hooks')).toBeLessThan(withProse.indexOf('## Patterns'));
    });
  });

  describe('the brand layer', () => {
    const readme = [
      '# Brand',
      '',
      '## CONTENT FUNDAMENTALS',
      '',
      '### Voice',
      '',
      '- The voice is Miltinson Technologies.',
      '',
      '---',
      '',
      '## VISUAL FOUNDATIONS',
      '',
      'Not voice.',
    ].join('\n');

    const withBrand = llmsFull({
      manifest,
      contracts,
      tokens,
      brand: {
        readme,
        note: 'The brand source lives here.',
        artifacts: [
          {
            path: 'ui_kits/webapp/index.html',
            title: 'Web App UI Kit',
            ships: true,
            components: ['Sidebar', 'TopBar'],
          },
          { path: 'guidelines/brand-voice.html', title: 'Brand voice', ships: false },
        ],
      },
    });

    it('omits the brand section entirely when the caller has no brand input', () => {
      expect(text).not.toContain('## Brand');
    });

    it('carries the voice rules, the caller note, and the artifact inventory', () => {
      expect(withBrand).toContain('## Brand');
      expect(withBrand).toContain('The voice is Miltinson Technologies.');
      expect(withBrand).toContain('The brand source lives here.');
      expect(withBrand).toContain(
        '- ui_kits/webapp/index.html — Web App UI Kit (components: Sidebar, TopBar)',
      );
    });

    it('marks repo-only artifacts so an agent reading a tarball never chases them', () => {
      expect(withBrand).toContain(
        '- guidelines/brand-voice.html — Brand voice [repo-only — not in the published package]',
      );
      expect(withBrand).not.toContain('Web App UI Kit (components: Sidebar, TopBar) [repo-only');
    });

    it('does not leak the visual foundations section in as voice', () => {
      expect(brandVoice(readme)).toContain('Miltinson Technologies');
      expect(brandVoice(readme)).not.toContain('Not voice.');
    });

    it('throws rather than silently losing the voice rules', () => {
      expect(() => brandVoice('# A readme with no fundamentals')).toThrow(/CONTENT FUNDAMENTALS/);
    });
  });
});
