#!/usr/bin/env node
/* Regenerates src/fonts.css, src/fonts/, and the design-system-docs mirror
 * from the pinned @fontsource-variable packages.
 *
 * tokens.css @imports './fonts.css' so that importing tokens.css is enough to
 * load the webfonts from the consumer's own origin — no Google Fonts request.
 * The @fontsource-variable packages are the source of truth for the woff2
 * files and their unicode-range subsets; this script rewrites their
 * declarations onto the family names the token stacks use ('Geist Variable'
 * would match nothing in tokens.css) and copies the files in. Everything it
 * writes is committed, like src/tokens.json — fonts.test.mjs pins the
 * committed copies back to the packages, so a fontsource bump that forgets to
 * rerun this script fails the build.
 *
 * design-system-docs/fonts{,.css} are per-file symlinks maintained here, the
 * way colors_and_type.css mirrors tokens.css: the brand cards, the packed
 * skill, and the docs site all resolve './fonts.css' from that folder, and
 * their staging steps copy dereferenced.
 */

import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { format, resolveConfig } from 'prettier';

const packageDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(packageDir, 'src');
const fontsDir = join(srcDir, 'fonts');
const docsDir = join(packageDir, '..', '..', 'design-system-docs');

/* The wght axis, normal style — parity with what the Google Fonts @import
   served (it named no ital axis either; oblique falls back to synthesis). */
const FAMILIES = [
  { family: 'Geist', source: '@fontsource-variable/geist', slug: 'geist' },
  {
    family: 'JetBrains Mono',
    source: '@fontsource-variable/jetbrains-mono',
    slug: 'jetbrains-mono',
  },
];

const resolve = createRequire(import.meta.url).resolve;

rmSync(fontsDir, { recursive: true, force: true });
mkdirSync(fontsDir, { recursive: true });

const sections = [];
const shipped = [];

for (const { family, source, slug } of FAMILIES) {
  const sourceDir = dirname(resolve(`${source}/package.json`));
  const faces = readFileSync(join(sourceDir, 'wght.css'), 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .match(/@font-face\s*\{[^}]*\}/g);
  if (!faces?.length) {
    throw new Error(`build-fonts: no @font-face blocks in ${source}/wght.css`);
  }

  const rewritten = faces.map((face) => {
    const basename = face.match(/url\(\.\/files\/([^)]+)\)/)?.[1];
    if (!basename) {
      throw new Error(`build-fonts: no ./files/ url in a ${source} @font-face block`);
    }
    copyFileSync(join(sourceDir, 'files', basename), join(fontsDir, basename));
    shipped.push(basename);
    return face
      .replace(/font-family:\s*[^;]+;/, `font-family: '${family}';`)
      .replace(/url\(\.\/files\//, 'url(./fonts/')
      .replace(/\{\s*/, '{\n  ')
      .replace(/;\s*(?=\S)/g, ';\n  ')
      .replace(/;\s*\}/, ';\n}');
  });

  copyFileSync(join(sourceDir, 'LICENSE'), join(fontsDir, `LICENSE-${slug}.txt`));
  sections.push(
    `/* --- ${family} — ${source} ------------------------------ */\n\n${rewritten.join('\n\n')}`,
  );
}

writeFileSync(
  join(srcDir, 'fonts.css'),
  /* Through prettier — with the repo's own config — so the committed file
     passes `format:check` however that config evolves. */
  await format(
    `/* GENERATED by packages/tokens/scripts/build-fonts.mjs. Do not edit by hand.
   @font-face for the families tokens.css names, self-hosted from src/fonts/.
   Faces and unicode-range subsets come from the pinned @fontsource-variable
   packages; licenses ship alongside the files (SIL OFL 1.1). */

${sections.join('\n\n')}
`,
    { ...(await resolveConfig(join(srcDir, 'fonts.css'))), parser: 'css' },
  ),
);

/* The brand mirror: relative symlinks, recreated from scratch each run so a
   removed face cannot leave a dangling link behind. */
const docsFonts = join(docsDir, 'fonts');
rmSync(docsFonts, { recursive: true, force: true });
rmSync(join(docsDir, 'fonts.css'), { force: true });
mkdirSync(docsFonts);
symlinkSync(join('..', 'packages', 'tokens', 'src', 'fonts.css'), join(docsDir, 'fonts.css'));
for (const entry of readdirSync(fontsDir).sort()) {
  symlinkSync(
    join('..', '..', 'packages', 'tokens', 'src', 'fonts', entry),
    join(docsFonts, entry),
  );
}

process.stdout.write(
  `tokens: wrote src/fonts.css (${shipped.length} faces), src/fonts/, and the design-system-docs mirror\n`,
);
