import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { lockedVersionFor, parseLockfile, readLockfile } from './lockfile.mjs';

const PNPM_V9 = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:

  .:
    dependencies:
      '@elirobinson/react':
        specifier: ^1.3.0
        version: 1.3.0
      react:
        specifier: ^19.2.5
        version: 19.2.5
    devDependencies:
      '@elirobinson/tokens':
        specifier: ^0.3.0
        version: 0.3.0

packages:

  '@elirobinson/react@2.0.1':
    resolution: {integrity: sha512-notthisone, tarball: https://npm.pkg.github.com/x.tgz}
`;

const PNPM_V6 = `lockfileVersion: '6.0'

dependencies:
  '@elirobinson/react':
    specifier: ^1.3.0
    version: 1.3.0

devDependencies:
  '@elirobinson/tokens':
    specifier: ^0.3.0
    version: 0.3.0
`;

const NPM_V3 = JSON.stringify({
  lockfileVersion: 3,
  packages: {
    '': { dependencies: { '@elirobinson/react': '^1.3.0' } },
    'node_modules/@elirobinson/react': { version: '1.3.0', resolved: 'https://x/react.tgz' },
    'node_modules/@elirobinson/tokens': { version: '0.3.0' },
    'node_modules/something/node_modules/@elirobinson/react': { version: '9.9.9' },
  },
});

const YARN_CLASSIC = `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


"@elirobinson/react@^1.3.0":
  version "1.3.0"
  resolved "https://npm.pkg.github.com/@elirobinson/react/-/react-1.3.0.tgz"

"@elirobinson/tokens@^0.3.0":
  version "0.3.0"
  resolved "https://npm.pkg.github.com/@elirobinson/tokens/-/tokens-0.3.0.tgz"
`;

const YARN_BERRY = `__metadata:
  version: 8

"@elirobinson/react@npm:^1.3.0":
  version: 1.3.0
  resolution: "@elirobinson/react@npm:1.3.0"
`;

describe('parseLockfile — pnpm', () => {
  it('resolves the root importer’s dependencies and devDependencies', () => {
    const lock = parseLockfile(PNPM_V9, 'pnpm');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
    expect(lockedVersionFor(lock, '@elirobinson/tokens', '^0.3.0')).toBe('0.3.0');
  });

  it('reads the importer entry rather than a version in the packages section', () => {
    // `packages:` lists every version in the graph, including ones nothing
    // depends on directly. Only the importer says what the root installs.
    expect(
      lockedVersionFor(parseLockfile(PNPM_V9, 'pnpm'), '@elirobinson/react', '^1.3.0'),
    ).not.toBe('2.0.1');
  });

  it('strips the peer-dependency suffix pnpm appends to a resolved version', () => {
    const lock = parseLockfile(
      `importers:
  .:
    dependencies:
      '@elirobinson/react':
        specifier: ^1.3.0
        version: 1.3.0(react@19.2.5)(react-dom@19.2.5(react@19.2.5))
`,
      'pnpm',
    );
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
  });

  it('reads the pre-importers layout used by older pnpm lockfiles', () => {
    const lock = parseLockfile(PNPM_V6, 'pnpm');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
    expect(lockedVersionFor(lock, '@elirobinson/tokens', '^0.3.0')).toBe('0.3.0');
  });

  it('treats a workspace link as unresolvable rather than as a version', () => {
    const lock = parseLockfile(
      `importers:
  .:
    dependencies:
      '@elirobinson/react':
        specifier: workspace:*
        version: link:packages/react
`,
      'pnpm',
    );
    expect(lockedVersionFor(lock, '@elirobinson/react', 'workspace:*')).toBeNull();
  });
});

describe('parseLockfile — npm', () => {
  it('resolves top-level installs from the packages map', () => {
    const lock = parseLockfile(NPM_V3, 'npm');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
    expect(lockedVersionFor(lock, '@elirobinson/tokens', '^0.3.0')).toBe('0.3.0');
  });

  it('ignores a nested copy installed for some other package', () => {
    expect(lockedVersionFor(parseLockfile(NPM_V3, 'npm'), '@elirobinson/react', '^1.3.0')).not.toBe(
      '9.9.9',
    );
  });

  it('reads the v1 dependencies layout', () => {
    const lock = parseLockfile(
      JSON.stringify({
        lockfileVersion: 1,
        dependencies: { '@elirobinson/react': { version: '1.3.0' } },
      }),
      'npm',
    );
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
  });

  it('skips a workspace link, which has no published version', () => {
    const lock = parseLockfile(
      JSON.stringify({
        lockfileVersion: 3,
        packages: {
          'node_modules/@elirobinson/react': { resolved: 'packages/react', link: true },
        },
      }),
      'npm',
    );
    expect(lockedVersionFor(lock, '@elirobinson/react', 'workspace:*')).toBeNull();
  });
});

describe('parseLockfile — yarn', () => {
  it('reads the classic v1 format', () => {
    const lock = parseLockfile(YARN_CLASSIC, 'yarn');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
    expect(lockedVersionFor(lock, '@elirobinson/tokens', '^0.3.0')).toBe('0.3.0');
  });

  it('reads the berry format', () => {
    const lock = parseLockfile(YARN_BERRY, 'yarn');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
  });

  it('picks the entry matching the declared range when a name is locked twice', () => {
    const lock = parseLockfile(
      `"@elirobinson/react@^1.3.0":
  version "1.9.0"

"@elirobinson/react@^2.0.0":
  version "2.0.1"
`,
      'yarn',
    );
    expect(lockedVersionFor(lock, '@elirobinson/react', '^2.0.0')).toBe('2.0.1');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.9.0');
  });

  it('refuses to guess when a name is locked twice and neither entry matches', () => {
    const lock = parseLockfile(
      `"@elirobinson/react@^1.3.0":
  version "1.9.0"

"@elirobinson/react@^2.0.0":
  version "2.0.1"
`,
      'yarn',
    );
    expect(lockedVersionFor(lock, '@elirobinson/react', '^3.0.0')).toBeNull();
  });

  it('handles a single header naming several ranges', () => {
    const lock = parseLockfile(
      `"@elirobinson/react@^1.3.0", "@elirobinson/react@^1.4.0":
  version "1.9.0"
`,
      'yarn',
    );
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.4.0')).toBe('1.9.0');
  });
});

describe('lockedVersionFor', () => {
  it('returns null for a package the lockfile does not mention', () => {
    expect(lockedVersionFor(parseLockfile(PNPM_V9, 'pnpm'), '@elirobinson/absent', '^1.0.0')).toBe(
      null,
    );
  });

  it('returns null when there is no lockfile at all', () => {
    expect(lockedVersionFor(null, '@elirobinson/react', '^1.3.0')).toBeNull();
  });
});

describe('readLockfile', () => {
  function repoWith(filename, contents) {
    const dir = mkdtempSync(join(tmpdir(), 'ds-lock-'));
    writeFileSync(join(dir, filename), contents);
    return dir;
  }

  it('finds and parses pnpm-lock.yaml', () => {
    const lock = readLockfile(repoWith('pnpm-lock.yaml', PNPM_V9));
    expect(lock.kind).toBe('pnpm');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
  });

  it('finds and parses package-lock.json', () => {
    const lock = readLockfile(repoWith('package-lock.json', NPM_V3));
    expect(lock.kind).toBe('npm');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
  });

  it('finds and parses yarn.lock', () => {
    const lock = readLockfile(repoWith('yarn.lock', YARN_CLASSIC));
    expect(lock.kind).toBe('yarn');
    expect(lockedVersionFor(lock, '@elirobinson/react', '^1.3.0')).toBe('1.3.0');
  });

  it('returns null when the directory has no lockfile', () => {
    expect(readLockfile(mkdtempSync(join(tmpdir(), 'ds-lock-')))).toBeNull();
  });

  it('returns null rather than throwing when the lockfile is unreadable', () => {
    // A corrupt lockfile should degrade to "no locked version", which the
    // caller already handles, not take the whole command down.
    expect(readLockfile(repoWith('package-lock.json', '{ not json'))).toBeNull();
  });
});
